server:
  port: 8085

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: JvK7U7H4YzW2pB9w2FSe34gV5+N0pI1A1rYgE3zdfhQ=
  expiration-ms: 86400000
